# This panelConfig is intended for use with Svg1. It differs from the main panelConfig
# in that it uses grafana suplied RandomWalk time-series. This is useful for demonstrating
# that the panel works with externally provided time-series. However as we have no say on
# the range of values, it's not that useful as a demonstrator of thresholds.
#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
  docs:
    link:
      url: "https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/README.md"
  sallent:
    dataRef: "temperature_0"
    label:
      separator: "cr"
      units: "m^3"
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  etap_bagesllobregat_1:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  etap_bagesllobregat_2:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_aigua_crua1:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_aigua_crua_2:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  arqueta_aigua_crua:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  bombament_aigua_crua:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_cabrianes:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_cabrianes1:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_cabrianes_2:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_horta_avinyo:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_soler:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_turic2:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_paloma:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_can_vila:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_paloma:
    dataRef: "temperature_0"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_pirineu:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_pirineu:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_vista_pirineu1:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_vista_pirineu2:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_grau_elevat:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_grau_elevat:
    dataRef: "temperature_0"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  d_grau:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
  b_grau_emergencia:
    dataRef: "temperature_1"
    label:
      separator: "cr"
      units: "m^3"  
      decimalPoints: 1
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "red", level: 19.99}
        - {color: "#006400", level: 20}
        - {color: "#006400", level: 40}
        - {color: "red", level: 40.01}
    fillColor:
      thresholds:
        - {color: "blue", level: 0}
    link: *grafana-home
